/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jbaiter.kenlm.jni;

public class FullScoreReturn {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public FullScoreReturn(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FullScoreReturn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KenLMJNI.delete_FullScoreReturn(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setProb(float value) {
    KenLMJNI.FullScoreReturn_prob_set(swigCPtr, this, value);
  }

  public float getProb() {
    return KenLMJNI.FullScoreReturn_prob_get(swigCPtr, this);
  }

  public void setNgram_length(short value) {
    KenLMJNI.FullScoreReturn_ngram_length_set(swigCPtr, this, value);
  }

  public short getNgram_length() {
    return KenLMJNI.FullScoreReturn_ngram_length_get(swigCPtr, this);
  }

  public FullScoreReturn() {
    this(KenLMJNI.new_FullScoreReturn(), true);
  }

}
