/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jbaiter.kenlm.jni;

public class KenLM {
  public static java.math.BigInteger hash_value(State state) {
    return KenLMJNI.hash_value(State.getCPtr(state), state);
  }

  public static Model LoadVirtual(String file_name, Config config) throws com.github.jbaiter.kenlm.ModelException {
    long cPtr = KenLMJNI.LoadVirtual__SWIG_0(file_name, Config.getCPtr(config), config);
    return (cPtr == 0) ? null : new Model(cPtr, true);
  }

  public static Model LoadVirtual(String file_name) throws com.github.jbaiter.kenlm.ModelException {
    long cPtr = KenLMJNI.LoadVirtual__SWIG_1(file_name);
    return (cPtr == 0) ? null : new Model(cPtr, true);
  }

}
