/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.github.jbaiter.kenlm.jni;

public class SWIGTYPE_p_void {
  private transient long swigCPtr;

  public SWIGTYPE_p_void(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_void() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_void obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

